config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'

  resources :users, only: [:new, :show, :create]
  resources :sessions, only: [:create]
  resources :inversions, only: [:index, :new, :create]
  resources :groups, only: [:index, :show, :new, :create]

  get 'sign_out' => 'sessions#destroy'
  get 'external' => 'inversions#external'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :user_id, :name, :icon, presence: true

  belongs_to :user
  has_many :group_inversions
  has_many :inversions, through: :group_inversions

  scope :alphabetical_order, -> { order(name: :asc) }
  scope :select_options, -> { all.map { |g| [g.name, g.id] }.unshift(['select a group...', 0]) }
end

app/models/group_inversion.rb
class GroupInversion < ApplicationRecord
  belongs_to :group
  belongs_to :inversion
end

app/models/inversion.rb
class Inversion < ApplicationRecord
  validates :author_id, :name, :amount, presence: true

  belongs_to :author, class_name: :User, foreign_key: :author_id
  has_many :group_inversions
  has_many :groups, through: :group_inversions

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :total, ->(current_user) { where(author_id: current_user).sum('amount') }
  scope :externals, lambda { |current_user|
                      left_joins(:group_inversions).where('group_inversions is null', author_id: current_user)
                    }
  scope :in_a_group, ->(id) { joins(:group_inversions).where('group_inversions.group_id' => id) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates_uniqueness_of :username

  has_many :inversions, dependent: :destroy
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def icons
    %w[baby
       basketball-ball
       burn
       candy-cane
       car-side
       chart-line]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all.alphabetical_order
  end

  def show
    @group = Group.find(params[:id])
    @inversions = Inversion.in_a_group(params[:id])
  end

  def new
    @icons = icons
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = session[:user_id]
    if @group.save
      flash[:success] = 'Group created succesfully!'
      redirect_to groups_path
    else
      flash[:danger] = 'Group was not created, please try again :c'
      redirect_to new_group_url
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/inversions_controller.rb
class InversionsController < ApplicationController
  include SessionsHelper
  def index
    @inversions = Inversion.where(author_id: current_user)
    @total = Inversion.total(current_user)
  end

  def external
    @inversions = Inversion.externals(current_user)
  end

  def new
    @groups = Group.select_options
  end

  def create
    @inversion = Inversion.new(inversion_params)
    @amount = params[:investment][:amount].to_f.round(2)
    @inversion.amount = @amount
    @inversion.author_id = session[:user_id]

    if @inversion.save
      @group = params[:investment][:group]
      if @group != 0
        @relation = GroupInversion.new(group_id: @group, inversion_id: @inversion.id)
        @relation.save
      end
      flash[:success] = 'Inversion created succesfully!'
    else
      flash[:danger] = 'Inversion was not created, please try again :c'
    end
    redirect_to inversions_path
  end

  private

  def inversion_params
    params.require(:investment).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  before_action :logged_user?, only: [:new]

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user
      session[:user_id] = @user.id
      session[:username] = @user.username
      flash[:success] = "Welcome #{@user.username}"
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Wrong login info'
      redirect_to root_path
    end
  end

  def destroy
    reset_session
    flash[:success] = 'Log out successfully'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:username] = @user.username
      flash[:success] = "User created, welcome #{@user.username}"
      redirect_to user_path(@user.id)
    else
      flash[:danger] = 'User was not created, please try another name :c'
      redirect_to new_user_url
    end
  end

  def new; end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def take_icon(id)
    Inversion.find(id).groups.map(&:icon)[0].nil? ? 'question' : Inversion.find(id).groups.map(&:icon)[0]
  end

  def take_username(id)
    User.find(id).username
  end

  def convert_datetime(datetime)
    datetime.strftime('%d %B %Y')
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/inversions_helper.rb
module InversionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    session[:user_id]
  end

  def logged_user?
    !current_user.nil?
  end

  def redirect_to_login
    controller.redirect_to root_path unless logged_user?
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<% redirect_to_login %>
<div class="row text-center my-4">
  <div class="col-12">
    <h1>All products</h1>
  </div>
</div>
<div class="row text-center mb-3">
  <div class="col-12">
    <a class="btn btn-primary" href="<%= new_group_url %>" role="button"
      >Add new product <i class="fas fa-plus"></i>
    </a>
  </div>
</div>
<div class="list-group">
  <% @groups.each do |g| %>
  <a
    href="<%= group_path(g) %>"
    class="list-group-item-action"
    aria-current="true"
  >
    <div class="row">
      <div class="col-2">
        <i class="fas fa-<%= g.icon %> fa-3x"></i>
      </div>
      <div class="col-10">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= g.name %></h5>
          <small><%= convert_datetime(g.created_at) %></small>
        </div>
      </div>
    </div>
  </a>
  <hr>
  <% end %>
</div>

app/views/groups/new.html.erb
<% redirect_to_login %>
<div class="row my-4">
    <div class="text-center">
      <h1 class="center">Create new product</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <%= form_for(:group, url: groups_path, method: 'POST') do |u| %>
      <div class="form-group">
        <%= u.text_field :name, autofocus: true, placeholder: 'Disney +',
        class: 'form-control', required: true, pattern: '[a-zA-Z0-9 ]{5,100}' %>
      </div>
      <div class="form-group mt-2">
        <%= u.select :icon, options_for_select(@icons) %>
      </div>
      <div class="actions mt-3">
        <%= u.submit class: "btn btn-primary", value: "Enter" %>
      </div>
      <% end %>
    </div>
    <div class="col-md-4"></div>
  </div>

app/views/groups/show.html.erb
<% redirect_to_login %>
<div class="row text-center mb-5">
  <div class="col-12">
    <h1>All inversions to <%= @group.name %></h1>
  </div>
</div>
<div class="list-group">
  <% @inversions.each do |i| %>
  <div class="row">
    <div class="col-2">
      <i class="fas fa-<%= take_icon(i.id) %> fa-3x"></i>
    </div>
    <div class="col-10">
      <div class="d-flex w-100 justify-content-between">
        <p class="mb-1"><%= take_username(i.author_id) %></p>
        <h5 class="mb-1"><%= i.name %></h5>
        <small><%= convert_datetime(i.created_at) %></small>
      </div>
      <p class="mb-1">$<%= i.amount %></p>
    </div>
  </div>
  <hr />
  <% end %>
</div>

app/views/inversions/external.html.erb
<% redirect_to_login %>
<div class="row text-center my-4">
    <div class="col-12">
      <h1>All my external investments</h1>
    </div>
  </div>
  <div class="row text-center mb-3">
    <div class="col-12">
      <a class="btn btn-primary" href="<%= new_inversion_url %>" role="button">Add new <i class="fas fa-plus"></i> </a>
    </div>
  </div>
  <div class="list-group">
    <% @inversions.each do |inv| %>
    <div class="row">
        <div class="col-2">
            <i class="fas fa-question fa-3x"></i>
        </div>
        <div class="col-10">
          <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1"><%= inv.name %></h5>
              <small>$<%= inv.amount %></small>
            </div>
            <p class="mb-1"><%= convert_datetime(inv.created_at) %></p>
        </div>
    </div>
    <hr>
    <% end %>
  </div>
  

app/views/inversions/index.html.erb
<% redirect_to_login %>
<div class="row text-center my-4">
  <div class="col-12">
    <h1>All my investments</h1>
  </div>
</div>
<div class="row text-center">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card text-center my-3 mx-auto" style="width: 18rem">
      <div class="card-body">
        <h5 class="card-title">Total inversion</h5>
        <h6 class="card-subtitle mb-2 text-muted">$<%= '%.2f' % @total %></h6>
        <p class="card-text">
            The total investment in all groups and those that have not yet been assigned.
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="row text-center mb-3">
  <div class="col-12">
    <a class="btn btn-primary" href="<%= new_inversion_url %>" role="button">Add new <i class="fas fa-plus"></i> </a>
  </div>
</div>
<div class="list-group">
  <% @inversions.each do |inv| %>
  <div class="row">
      <div class="col-2">
        <i class="fas fa-<%= take_icon(inv.id) %> fa-3x"></i>
      </div>
      <div class="col-10">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1"><%= inv.name %></h5>
            <small>$<%= '%.2f' % inv.amount %></small>
          </div>
          <p class="mb-1"><%= convert_datetime(inv.created_at) %></p>
      </div>
  </div>
  <hr>
  <% end %>
</div>

app/views/inversions/new.html.erb
<% redirect_to_login %>
<div class="row my-4">
  <div class="text-center">
    <h1 class="center">Create new investment</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_for(:investment, url: inversions_path, method: 'POST') do |u| %>
    <div class="form-group">
      <%= u.text_field :name, autofocus: true, placeholder: 'University investment...',
      class: 'form-control', required: true, pattern: '[a-zA-Z0-9 ]{5,100}' %>
    </div>
    <div class="form-group mt-2">
      <%= u.text_field :amount, placeholder: '350.99',
      class: 'form-control', required: true, pattern: '[0-9]{1,10}|[0-9]{1,10}\.[0-9]{2}' %>
    </div>
    <div class="form-group mt-2">
      <%= u.select :group, @groups %>
    </div>
    
    <div class="actions mt-3">
      <%= u.submit class: "btn btn-primary", value: "Enter" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Capstone Investments</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />
  </head>

  <body>
    <% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %> mb-0">
    <%= msg %>
  </div>
<% end %>
    <nav class="navbar navbar-dark bg-primary">
      <div class="d-flex container-fluid">
        <% if current_user %>
          <h1><a class="navbar-brand" href="<%= user_path(session[:user_id]) %>"><i class="fas fa-user fa-2x"></i></a></h1>
          <a href="<%= inversions_path %>" class="navbar-brand"><i class="fas fa-globe-americas fa-2x"></i></a>
          <a href="<%= external_path %>" class="navbar-brand"><i class="fas fa-external-link-alt fa-2x"></i></a>
          <a href="<%= groups_path %>" class="navbar-brand"><i class="fas fa-hands-helping fa-2x"></i></a>
          <a class="navbar-brand" href="<%= sign_out_url %>"><i class="fas fa-sign-out-alt fa-2x"></i></a>
        <% else %>
        <a class="navbar-brand" href="<%= root_path %>"><i class="fas fa-home"></i></a>
        <% end %>
      </div>
    </nav>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/transactions/external.html.erb
<div class="row text-center">
    <div class="col-12">
      <h1>All my investments without product assigned</h1>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="card text-center my-3 mx-auto" style="width: 18rem">
        <div class="card-body">
          <h5 class="card-title">Total inversion</h5>
          <h6 class="card-subtitle mb-2 text-muted">$ 600.00</h6>
          <p class="card-text">
              The total investment to those that have not yet been assigned.
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4"></div>
  </div>
  <div class="row text-center mb-3">
    <div class="col-12">
      <a class="btn btn-primary" href="#" role="button">Add new <i class="fas fa-plus"></i> </a>
    </div>
  </div>
  <div class="list-group">
    <a
      href="#"
      class="list-group-item list-group-item-action"
      aria-current="true"
    >
    <div class="row">
        <div class="col-2">
            <i class="fas fa-question fa-3x"></i>
        </div>
        <div class="col-10">
          <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Investment name</h5>
              <small>3 days ago</small>
            </div>
            <p class="mb-1">$350.00</p>
        </div>
    </div>
      
    </a>
  </div>
  

app/views/transactions/index.html.erb
<div class="row text-center">
  <div class="col-12">
    <h1>All my investments</h1>
  </div>
</div>
<div class="row text-center">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card text-center my-3 mx-auto" style="width: 18rem">
      <div class="card-body">
        <h5 class="card-title">Total inversion</h5>
        <h6 class="card-subtitle mb-2 text-muted">$ 600.00</h6>
        <p class="card-text">
            The total investment in all groups and those that have not yet been assigned.
        </p>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="row text-center mb-3">
  <div class="col-12">
    <a class="btn btn-primary" href="<%= new_transaction_url %>" role="button">Add new <i class="fas fa-plus"></i> </a>
  </div>
</div>
<div class="list-group">
  <a
    href="#"
    class="list-group-item list-group-item-action"
    aria-current="true"
  >
  <div class="row">
      <div class="col-2">
        <i class="fab fa-twitter fa-3x"></i>
      </div>
      <div class="col-10">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Investment name</h5>
            <small>3 days ago</small>
          </div>
          <p class="mb-1">$350.00</p>
      </div>
  </div>
    
  </a>
</div>

app/views/transactions/new.html.erb
<div class="row my-4">
  <div class="text-center">
    <h1 class="center">Create new investment</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_for(:investment, url: transactions_path, method: 'POST') do |u| %>
    <div class="form-group">
      <%= u.text_field :name, autofocus: true, placeholder: 'University investment...',
      class: 'form-control', required: true %>
    </div>
    <div class="form-group mt-2">
      <%= u.text_field :amount, placeholder: '$ 350.99',
      class: 'form-control', required: true %>
    </div>
    <div class="actions mt-3">
      <%= u.submit class: "btn btn-primary", value: "Enter" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/users/new.html.erb
<div class="row my-4">
  <div class="text-center">
    <h1 class="center">Create user</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_for(:user, url: users_path, method: 'POST') do |u| %>
    <div class="form-group">
      <%= u.text_field :username, autofocus: true, placeholder: 'Jason Bourne',
      class: 'form-control', required: true, pattern: '[a-zA-Z0-9 ]{4,100}' %>
    </div>
    <div class="actions mt-3">
      <%= u.submit class: "btn btn-primary", value: "Enter" %>
    </div>
    <% end %>
  </div>
  <div class="col-md-4"></div>
</div>

app/views/users/show.html.erb
<% redirect_to_login %>
<div class="row mt-5 text-center">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="card mx-auto" style="width: 18rem">
      <div class="card-body">
        <h5 class="card-title"><%= @user.username %></h5>
        <p class="card-text">
          Welcome to the best investment page in the world.
        </p>
      </div>
      <ul class="list-group list-group-flush text-center">
        <li class="list-group-item"><a href="<%= inversions_path %>" class="btn btn-primary">All my investments</a></li>
        <li class="list-group-item"><a href="<%= external_path %>" class="btn btn-primary">All my external investments</a></li>
        <li class="list-group-item"><a href="<%= groups_path %>" class="btn btn-primary">All products</a></li>
      </ul>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>